routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('post', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['name', 'body'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->paginate(10);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'body' => 'required|min:10'
        ]);

        Post::create($request->only(['name', 'body']));

        return redirect()->route('post.index')->with('success', 'Post created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'name' => 'required',
            'body' => 'required|min:10',
        ]);

        $post->update($request->only(['name', 'body']));
        return redirect()->route('post.index')->with('success', 'Post has been updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('post.index')->with('success', 'Post has been deleted successfully!');
    }
}

resources/views/posts/create.blade.php
@extends('posts.master')

@section('body')

<div class="card">
  <div class="card-header">
      <div class="float-right">
          <a href="{{ route('post.index') }}" class="btn btn-primary btn-sm">Back to Posts</a>
      </div>
     Create Post
  </div>
  <div class="card-body">

    @if ($errors->any())
    <div class="alert alert-danger">
        <p>
            <strong>Input Error!</strong>
        </p>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

      <form method="POST" action="{{ route('post.store') }}">
            @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
        </div>

         <div class="form-group">
            <label for="body">Body</label>
            <textarea class="form-control" id="body" name="body" rows="5">{{ old('body') }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>

      </form>
  </div>
@endsection

resources/views/posts/edit.blade.php
@extends('posts.master')

@section('body')

<div class="card">
  <div class="card-header">
      <div class="float-right">
          <a href="{{ route('post.index') }}" class="btn btn-primary btn-sm">Back to Posts</a>
      </div>
     Update Post
  </div>
  <div class="card-body">

    @if ($errors->any())
    <div class="alert alert-danger">
        <p>
            <strong>Input Error!</strong>
        </p>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('post.update',$post->id) }}" method="POST">
        @csrf @method('PUT')

        <div class="form-group">
            <label for="name">Name</label>
            <input
                type="text"
                class="form-control"
                id="name"
                name="name"
                value="{{ $post->name }}"
            />
        </div>

        <div class="form-group">
            <label for="body">Body</label>
            <textarea
                class="form-control"
                id="body"
                name="body"
                rows="5"
                >{{ $post->body }}</textarea
            >
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('posts.master') 

@section('body')

<div class="card">
    <div class="card-header">
        <div class="float-right">
            <a href="{{ route('post.create') }}" class="btn btn-primary btn-sm"
                >Add</a>
        </div>
        Posts
    </div>
    <div class="card-body">
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Action</th>
            </tr>
            </thead>
            @foreach ($posts as $key => $post)
            <tbody>
            <tr>
                <td>
                    {{ $key + 1 }}
                </td>
                <td>
                    <a href="{{ route('post.show',$post->id) }}">
                    {{ $post->name }}
                    </a>
                </td>
                <td>

                <a
                    style="background-color: #FF69B4; color: white"
                    class="btn btn-sm"
                    href="{{ route('post.show',$post->id) }}"
                    >Show</a>


                    <a
                    class="btn btn-primary btn-sm"
                    href="{{ route('post.edit',$post->id) }}"
                    >Edit</a>

                       <form
                            action="{{ route('post.destroy',$post->id) }}"
                            method="POST"
                            style="display: inline;"
                        >
                        @csrf @method('DELETE')

                        <button type="submit" class="btn btn-danger btn-sm">
                            Delete
                        </button>
                </td>
            </tr>
            </tbody>
            @endforeach
        </table>
        {!! $posts->links() !!}
    </div>
    @endsection
</div>

resources/views/posts/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Exclusive Laravel 6 CRUD Application Learning Guide - itechempires.com</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {{--  <div class="jumbotron">
                        <h1 class="display-6">Exclusive Laravel 6 CRUD Application Demo</h1>
                        <p class="lead">
                        Practical laravel 6 application to learn laravel crud application.
                        </p>
                    </div>  --}}
                    @yield('body')
                </div>
            </div>
        </div>
    </div>
</body>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
</html>

resources/views/posts/show.blade.php
@extends('posts.master')

@section('body')

<div class="card">
  <div class="card-header">
      <div class="float-right">
          <a href="{{ route('post.index') }}" class="btn btn-primary btn-sm">Back to Posts</a>
      </div>
      Post
  </div>
  <div class="card-body">

    <h2>{{ $post->name }}</h2>

    <p>
        {{ $post->body }}
    </p>
</div>
@endsection